### 选择以下两种方式获取token ###
### 1.1 密码模式（以user身份登陆）
POST http://localhost:8080/oauth/token?grant_type=password&client_id=appId&client_secret=appSecret&scope=any
Content-Type: application/x-www-form-urlencoded
Accept: application/json

username=user&password=user

> {%
client.global.set("access_token", response.body.access_token);
client.global.set("refresh_token", response.body.refresh_token);
%}

### 1.2 客户端模式（该模式没有refresh_token）
POST http://localhost:8080/oauth/token?grant_type=client_credentials&client_id=appId&client_secret=appSecret&scope=any
 {%
client.g
>lobal.set("access_token", response.body.access_token);
%}

### 2.访问受保护资源（USER权限的用户可以访问）
GET http://localhost:8080/res/user/hello?access_token={{access_token}}

### 3.访问受保护资源（ADMIN权限的用户可以访问）
GET http://localhost:8080/res/admin/hello?access_token={{access_token}}

### 4.使用 refresh_token 刷新 access_token
POST http://localhost:8080/oauth/token?grant_type=refresh_token&client_id=appId&client_secret=appSecret&refresh_token={{refresh_token}}
#Content-Type: application/x-www-form-urlencoded
#Accept: application/json
#
#username=user&password=user