#开启SSL后需要先访问https关闭浏览器警告，才能建立wss连接
server:
  port: 8443
  ssl:
    enabled: false
    key-store: classpath:keystore.jks
    key-store-password: 123456
    key-password: 123456
    key-alias: tomcat
  http2:
    enabled: true
